curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/ucur.1982.nc --output godas/u/u_1982.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/vcur.1982.nc --output godas/v/v_1982.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/pottmp.1982.nc --output godas/sst/pottmp_1982.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/dbss_obml.1982.nc --output godas/mld/mld_1982.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/ucur.1983.nc --output godas/u/u_1983.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/vcur.1983.nc --output godas/v/v_1983.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/pottmp.1983.nc --output godas/sst/pottmp_1983.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/dbss_obml.1983.nc --output godas/mld/mld_1983.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/ucur.1984.nc --output godas/u/u_1984.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/vcur.1984.nc --output godas/v/v_1984.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/pottmp.1984.nc --output godas/sst/pottmp_1984.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/dbss_obml.1984.nc --output godas/mld/mld_1984.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/ucur.1985.nc --output godas/u/u_1985.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/vcur.1985.nc --output godas/v/v_1985.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/pottmp.1985.nc --output godas/sst/pottmp_1985.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/dbss_obml.1985.nc --output godas/mld/mld_1985.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/ucur.1986.nc --output godas/u/u_1986.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/vcur.1986.nc --output godas/v/v_1986.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/pottmp.1986.nc --output godas/sst/pottmp_1986.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/dbss_obml.1986.nc --output godas/mld/mld_1986.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/ucur.1987.nc --output godas/u/u_1987.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/vcur.1987.nc --output godas/v/v_1987.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/pottmp.1987.nc --output godas/sst/pottmp_1987.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/dbss_obml.1987.nc --output godas/mld/mld_1987.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/ucur.1988.nc --output godas/u/u_1988.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/vcur.1988.nc --output godas/v/v_1988.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/pottmp.1988.nc --output godas/sst/pottmp_1988.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/dbss_obml.1988.nc --output godas/mld/mld_1988.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/ucur.1989.nc --output godas/u/u_1989.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/vcur.1989.nc --output godas/v/v_1989.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/pottmp.1989.nc --output godas/sst/pottmp_1989.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/dbss_obml.1989.nc --output godas/mld/mld_1989.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/ucur.1990.nc --output godas/u/u_1990.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/vcur.1990.nc --output godas/v/v_1990.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/pottmp.1990.nc --output godas/sst/pottmp_1990.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/dbss_obml.1990.nc --output godas/mld/mld_1990.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/ucur.1991.nc --output godas/u/u_1991.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/vcur.1991.nc --output godas/v/v_1991.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/pottmp.1991.nc --output godas/sst/pottmp_1991.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/dbss_obml.1991.nc --output godas/mld/mld_1991.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/ucur.1992.nc --output godas/u/u_1992.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/vcur.1992.nc --output godas/v/v_1992.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/pottmp.1992.nc --output godas/sst/pottmp_1992.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/dbss_obml.1992.nc --output godas/mld/mld_1992.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/ucur.1993.nc --output godas/u/u_1993.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/vcur.1993.nc --output godas/v/v_1993.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/pottmp.1993.nc --output godas/sst/pottmp_1993.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/dbss_obml.1993.nc --output godas/mld/mld_1993.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/ucur.1994.nc --output godas/u/u_1994.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/vcur.1994.nc --output godas/v/v_1994.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/pottmp.1994.nc --output godas/sst/pottmp_1994.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/dbss_obml.1994.nc --output godas/mld/mld_1994.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/ucur.1995.nc --output godas/u/u_1995.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/vcur.1995.nc --output godas/v/v_1995.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/pottmp.1995.nc --output godas/sst/pottmp_1995.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/dbss_obml.1995.nc --output godas/mld/mld_1995.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/ucur.1996.nc --output godas/u/u_1996.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/vcur.1996.nc --output godas/v/v_1996.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/pottmp.1996.nc --output godas/sst/pottmp_1996.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/dbss_obml.1996.nc --output godas/mld/mld_1996.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/ucur.1997.nc --output godas/u/u_1997.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/vcur.1997.nc --output godas/v/v_1997.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/pottmp.1997.nc --output godas/sst/pottmp_1997.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/dbss_obml.1997.nc --output godas/mld/mld_1997.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/ucur.1998.nc --output godas/u/u_1998.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/vcur.1998.nc --output godas/v/v_1998.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/pottmp.1998.nc --output godas/sst/pottmp_1998.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/dbss_obml.1998.nc --output godas/mld/mld_1998.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/ucur.1999.nc --output godas/u/u_1999.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/vcur.1999.nc --output godas/v/v_1999.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/pottmp.1999.nc --output godas/sst/pottmp_1999.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/dbss_obml.1999.nc --output godas/mld/mld_1999.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/ucur.2000.nc --output godas/u/u_2000.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/vcur.2000.nc --output godas/v/v_2000.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/pottmp.2000.nc --output godas/sst/pottmp_2000.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/dbss_obml.2000.nc --output godas/mld/mld_2000.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/ucur.2001.nc --output godas/u/u_2001.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/vcur.2001.nc --output godas/v/v_2001.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/pottmp.2001.nc --output godas/sst/pottmp_2001.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/dbss_obml.2001.nc --output godas/mld/mld_2001.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/ucur.2002.nc --output godas/u/u_2002.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/vcur.2002.nc --output godas/v/v_2002.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/pottmp.2002.nc --output godas/sst/pottmp_2002.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/dbss_obml.2002.nc --output godas/mld/mld_2002.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/ucur.2003.nc --output godas/u/u_2003.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/vcur.2003.nc --output godas/v/v_2003.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/pottmp.2003.nc --output godas/sst/pottmp_2003.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/dbss_obml.2003.nc --output godas/mld/mld_2003.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/ucur.2004.nc --output godas/u/u_2004.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/vcur.2004.nc --output godas/v/v_2004.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/pottmp.2004.nc --output godas/sst/pottmp_2004.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/dbss_obml.2004.nc --output godas/mld/mld_2004.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/ucur.2005.nc --output godas/u/u_2005.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/vcur.2005.nc --output godas/v/v_2005.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/pottmp.2005.nc --output godas/sst/pottmp_2005.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/dbss_obml.2005.nc --output godas/mld/mld_2005.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/ucur.2006.nc --output godas/u/u_2006.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/vcur.2006.nc --output godas/v/v_2006.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/pottmp.2006.nc --output godas/sst/pottmp_2006.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/dbss_obml.2006.nc --output godas/mld/mld_2006.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/ucur.2007.nc --output godas/u/u_2007.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/vcur.2007.nc --output godas/v/v_2007.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/pottmp.2007.nc --output godas/sst/pottmp_2007.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/dbss_obml.2007.nc --output godas/mld/mld_2007.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/ucur.2008.nc --output godas/u/u_2008.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/vcur.2008.nc --output godas/v/v_2008.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/pottmp.2008.nc --output godas/sst/pottmp_2008.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/dbss_obml.2008.nc --output godas/mld/mld_2008.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/ucur.2009.nc --output godas/u/u_2009.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/vcur.2009.nc --output godas/v/v_2009.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/pottmp.2009.nc --output godas/sst/pottmp_2009.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/dbss_obml.2009.nc --output godas/mld/mld_2009.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/ucur.2010.nc --output godas/u/u_2010.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/vcur.2010.nc --output godas/v/v_2010.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/pottmp.2010.nc --output godas/sst/pottmp_2010.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/dbss_obml.2010.nc --output godas/mld/mld_2010.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/ucur.2011.nc --output godas/u/u_2011.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/vcur.2011.nc --output godas/v/v_2011.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/pottmp.2011.nc --output godas/sst/pottmp_2011.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/dbss_obml.2011.nc --output godas/mld/mld_2011.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/ucur.2012.nc --output godas/u/u_2012.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/vcur.2012.nc --output godas/v/v_2012.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/pottmp.2012.nc --output godas/sst/pottmp_2012.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/dbss_obml.2012.nc --output godas/mld/mld_2012.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/ucur.2013.nc --output godas/u/u_2013.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/vcur.2013.nc --output godas/v/v_2013.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/pottmp.2013.nc --output godas/sst/pottmp_2013.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/dbss_obml.2013.nc --output godas/mld/mld_2013.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/ucur.2014.nc --output godas/u/u_2014.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/vcur.2014.nc --output godas/v/v_2014.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/pottmp.2014.nc --output godas/sst/pottmp_2014.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/dbss_obml.2014.nc --output godas/mld/mld_2014.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/ucur.2015.nc --output godas/u/u_2015.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/vcur.2015.nc --output godas/v/v_2015.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/pottmp.2015.nc --output godas/sst/pottmp_2015.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/dbss_obml.2015.nc --output godas/mld/mld_2015.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/ucur.2016.nc --output godas/u/u_2016.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/vcur.2016.nc --output godas/v/v_2016.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/pottmp.2016.nc --output godas/sst/pottmp_2016.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/dbss_obml.2016.nc --output godas/mld/mld_2016.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/ucur.2017.nc --output godas/u/u_2017.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/vcur.2017.nc --output godas/v/v_2017.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/pottmp.2017.nc --output godas/sst/pottmp_2017.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/dbss_obml.2017.nc --output godas/mld/mld_2017.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/ucur.2018.nc --output godas/u/u_2018.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/vcur.2018.nc --output godas/v/v_2018.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/pottmp.2018.nc --output godas/sst/pottmp_2018.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/dbss_obml.2018.nc --output godas/mld/mld_2018.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/ucur.2019.nc --output godas/u/u_2019.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/vcur.2019.nc --output godas/v/v_2019.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/pottmp.2019.nc --output godas/sst/pottmp_2019.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/dbss_obml.2019.nc --output godas/mld/mld_2019.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/ucur.2020.nc --output godas/u/u_2020.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/vcur.2020.nc --output godas/v/v_2020.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/pottmp.2020.nc --output godas/sst/pottmp_2020.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/godas/dbss_obml.2020.nc --output godas/mld/mld_2020.nc
