curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.1951.nc --output ncar/SW/SW_1951.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.1951.nc --output ncar/LW/LW_1951.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.1952.nc --output ncar/SW/SW_1952.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.1952.nc --output ncar/LW/LW_1952.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.1953.nc --output ncar/SW/SW_1953.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.1953.nc --output ncar/LW/LW_1953.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.1954.nc --output ncar/SW/SW_1954.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.1954.nc --output ncar/LW/LW_1954.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.1955.nc --output ncar/SW/SW_1955.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.1955.nc --output ncar/LW/LW_1955.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.1956.nc --output ncar/SW/SW_1956.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.1956.nc --output ncar/LW/LW_1956.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.1957.nc --output ncar/SW/SW_1957.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.1957.nc --output ncar/LW/LW_1957.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.1958.nc --output ncar/SW/SW_1958.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.1958.nc --output ncar/LW/LW_1958.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.1959.nc --output ncar/SW/SW_1959.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.1959.nc --output ncar/LW/LW_1959.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.1960.nc --output ncar/SW/SW_1960.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.1960.nc --output ncar/LW/LW_1960.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.1961.nc --output ncar/SW/SW_1961.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.1961.nc --output ncar/LW/LW_1961.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.1962.nc --output ncar/SW/SW_1962.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.1962.nc --output ncar/LW/LW_1962.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.1963.nc --output ncar/SW/SW_1963.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.1963.nc --output ncar/LW/LW_1963.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.1964.nc --output ncar/SW/SW_1964.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.1964.nc --output ncar/LW/LW_1964.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.1965.nc --output ncar/SW/SW_1965.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.1965.nc --output ncar/LW/LW_1965.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.1966.nc --output ncar/SW/SW_1966.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.1966.nc --output ncar/LW/LW_1966.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.1967.nc --output ncar/SW/SW_1967.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.1967.nc --output ncar/LW/LW_1967.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.1968.nc --output ncar/SW/SW_1968.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.1968.nc --output ncar/LW/LW_1968.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.1969.nc --output ncar/SW/SW_1969.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.1969.nc --output ncar/LW/LW_1969.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.1970.nc --output ncar/SW/SW_1970.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.1970.nc --output ncar/LW/LW_1970.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.1971.nc --output ncar/SW/SW_1971.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.1971.nc --output ncar/LW/LW_1971.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.1972.nc --output ncar/SW/SW_1972.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.1972.nc --output ncar/LW/LW_1972.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.1973.nc --output ncar/SW/SW_1973.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.1973.nc --output ncar/LW/LW_1973.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.1974.nc --output ncar/SW/SW_1974.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.1974.nc --output ncar/LW/LW_1974.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.1975.nc --output ncar/SW/SW_1975.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.1975.nc --output ncar/LW/LW_1975.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.1976.nc --output ncar/SW/SW_1976.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.1976.nc --output ncar/LW/LW_1976.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.1977.nc --output ncar/SW/SW_1977.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.1977.nc --output ncar/LW/LW_1977.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.1978.nc --output ncar/SW/SW_1978.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.1978.nc --output ncar/LW/LW_1978.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.1979.nc --output ncar/SW/SW_1979.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.1979.nc --output ncar/LW/LW_1979.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.1980.nc --output ncar/SW/SW_1980.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.1980.nc --output ncar/LW/LW_1980.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.1981.nc --output ncar/SW/SW_1981.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.1981.nc --output ncar/LW/LW_1981.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.1982.nc --output ncar/SW/SW_1982.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.1982.nc --output ncar/LW/LW_1982.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.1983.nc --output ncar/SW/SW_1983.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.1983.nc --output ncar/LW/LW_1983.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.1984.nc --output ncar/SW/SW_1984.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.1984.nc --output ncar/LW/LW_1984.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.1985.nc --output ncar/SW/SW_1985.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.1985.nc --output ncar/LW/LW_1985.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.1986.nc --output ncar/SW/SW_1986.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.1986.nc --output ncar/LW/LW_1986.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.1987.nc --output ncar/SW/SW_1987.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.1987.nc --output ncar/LW/LW_1987.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.1988.nc --output ncar/SW/SW_1988.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.1988.nc --output ncar/LW/LW_1988.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.1989.nc --output ncar/SW/SW_1989.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.1989.nc --output ncar/LW/LW_1989.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.1990.nc --output ncar/SW/SW_1990.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.1990.nc --output ncar/LW/LW_1990.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.1991.nc --output ncar/SW/SW_1991.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.1991.nc --output ncar/LW/LW_1991.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.1992.nc --output ncar/SW/SW_1992.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.1992.nc --output ncar/LW/LW_1992.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.1993.nc --output ncar/SW/SW_1993.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.1993.nc --output ncar/LW/LW_1993.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.1994.nc --output ncar/SW/SW_1994.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.1994.nc --output ncar/LW/LW_1994.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.1995.nc --output ncar/SW/SW_1995.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.1995.nc --output ncar/LW/LW_1995.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.1996.nc --output ncar/SW/SW_1996.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.1996.nc --output ncar/LW/LW_1996.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.1997.nc --output ncar/SW/SW_1997.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.1997.nc --output ncar/LW/LW_1997.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.1998.nc --output ncar/SW/SW_1998.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.1998.nc --output ncar/LW/LW_1998.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.1999.nc --output ncar/SW/SW_1999.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.1999.nc --output ncar/LW/LW_1999.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.2000.nc --output ncar/SW/SW_2000.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.2000.nc --output ncar/LW/LW_2000.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.2001.nc --output ncar/SW/SW_2001.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.2001.nc --output ncar/LW/LW_2001.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.2002.nc --output ncar/SW/SW_2002.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.2002.nc --output ncar/LW/LW_2002.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.2003.nc --output ncar/SW/SW_2003.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.2003.nc --output ncar/LW/LW_2003.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.2004.nc --output ncar/SW/SW_2004.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.2004.nc --output ncar/LW/LW_2004.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.2005.nc --output ncar/SW/SW_2005.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.2005.nc --output ncar/LW/LW_2005.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.2006.nc --output ncar/SW/SW_2006.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.2006.nc --output ncar/LW/LW_2006.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.2007.nc --output ncar/SW/SW_2007.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.2007.nc --output ncar/LW/LW_2007.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.2008.nc --output ncar/SW/SW_2008.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.2008.nc --output ncar/LW/LW_2008.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.2009.nc --output ncar/SW/SW_2009.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.2009.nc --output ncar/LW/LW_2009.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.2010.nc --output ncar/SW/SW_2010.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.2010.nc --output ncar/LW/LW_2010.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.2011.nc --output ncar/SW/SW_2011.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.2011.nc --output ncar/LW/LW_2011.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.2012.nc --output ncar/SW/SW_2012.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.2012.nc --output ncar/LW/LW_2012.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.2013.nc --output ncar/SW/SW_2013.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.2013.nc --output ncar/LW/LW_2013.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.2014.nc --output ncar/SW/SW_2014.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.2014.nc --output ncar/LW/LW_2014.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.2015.nc --output ncar/SW/SW_2015.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.2015.nc --output ncar/LW/LW_2015.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.2016.nc --output ncar/SW/SW_2016.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.2016.nc --output ncar/LW/LW_2016.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.2017.nc --output ncar/SW/SW_2017.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.2017.nc --output ncar/LW/LW_2017.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.2018.nc --output ncar/SW/SW_2018.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.2018.nc --output ncar/LW/LW_2018.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.2019.nc --output ncar/SW/SW_2019.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.2019.nc --output ncar/LW/LW_2019.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nswrs.sfc.gauss.2020.nc --output ncar/SW/SW_2020.nc
curl  -C - https://downloads.psl.noaa.gov//Datasets/ncep.reanalysis/Dailies/surface_gauss/nlwrs.sfc.gauss.2020.nc --output ncar/LW/LW_2020.nc
